<?php
/**
 * DirectEntitlementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Genba Digital Distribution API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DirectEntitlementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DirectEntitlementApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for directEntitlementActivateAsync
     *
     * Perform a direct entitlement activation.
     *
     */
    public function testDirectEntitlementActivateAsync()
    {
    }

    /**
     * Test case for directEntitlementPerformActivationActionAsync
     *
     * Perform an action on an activation.
     *
     */
    public function testDirectEntitlementPerformActivationActionAsync()
    {
    }

    /**
     * Test case for directEntitlementPerformRedemptionActionAsync
     *
     * Perform an action on a redemption.
     *
     */
    public function testDirectEntitlementPerformRedemptionActionAsync()
    {
    }

    /**
     * Test case for directEntitlementRedeemAsync
     *
     * Perform a direct entitlement redemption.
     *
     */
    public function testDirectEntitlementRedeemAsync()
    {
    }

    /**
     * Test case for directEntitlementRetrieveActivationAsync
     *
     * Retrieve a direct entitlement activation.
     *
     */
    public function testDirectEntitlementRetrieveActivationAsync()
    {
    }

    /**
     * Test case for directEntitlementRetrieveActivationByCtidAsync
     *
     * Retrieve a direct entitlement activation by its Client Transaction ID.
     *
     */
    public function testDirectEntitlementRetrieveActivationByCtidAsync()
    {
    }

    /**
     * Test case for directEntitlementRetrieveRedemptionAsync
     *
     * Retrieve a direct entitlement redemption.
     *
     */
    public function testDirectEntitlementRetrieveRedemptionAsync()
    {
    }

    /**
     * Test case for directEntitlementRetrieveRedemptionByCtidAsync
     *
     * Retrieve a direct entitlement redemption by its Client Transaction ID.
     *
     */
    public function testDirectEntitlementRetrieveRedemptionByCtidAsync()
    {
    }
}
