<?php
/**
 * DirectEntitlementRedemptionRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Genba Digital Distribution API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DirectEntitlementRedemptionRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DirectEntitlementRedemptionRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DirectEntitlementRedemptionRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DirectEntitlementRedemptionRequest"
     */
    public function testDirectEntitlementRedemptionRequest()
    {
    }

    /**
     * Test attribute "client_transaction_id"
     */
    public function testPropertyClientTransactionId()
    {
    }

    /**
     * Test attribute "etailer_id"
     */
    public function testPropertyEtailerId()
    {
    }

    /**
     * Test attribute "activation_id"
     */
    public function testPropertyActivationId()
    {
    }

    /**
     * Test attribute "redemption"
     */
    public function testPropertyRedemption()
    {
    }
}
