<?php
/**
 * LocalisationSetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Genba Digital Distribution API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LocalisationSetTest Class Doc Comment
 *
 * @category    Class
 * @description LocalisationSet
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocalisationSetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LocalisationSet"
     */
    public function testLocalisationSet()
    {
    }

    /**
     * Test attribute "spoken_language_set"
     */
    public function testPropertySpokenLanguageSet()
    {
    }

    /**
     * Test attribute "subtitle_language_set"
     */
    public function testPropertySubtitleLanguageSet()
    {
    }

    /**
     * Test attribute "menu_language_set"
     */
    public function testPropertyMenuLanguageSet()
    {
    }
}
