<?php
/**
 * ProductResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Genba Digital Distribution API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ProductResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductResponse"
     */
    public function testProductResponse()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "region_code"
     */
    public function testPropertyRegionCode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "digital_release_date"
     */
    public function testPropertyDigitalReleaseDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "platform"
     */
    public function testPropertyPlatform()
    {
    }

    /**
     * Test attribute "publisher"
     */
    public function testPropertyPublisher()
    {
    }

    /**
     * Test attribute "developer"
     */
    public function testPropertyDeveloper()
    {
    }

    /**
     * Test attribute "protection_system"
     */
    public function testPropertyProtectionSystem()
    {
    }

    /**
     * Test attribute "key_provider"
     */
    public function testPropertyKeyProvider()
    {
    }

    /**
     * Test attribute "genres"
     */
    public function testPropertyGenres()
    {
    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {
    }

    /**
     * Test attribute "global_trade_item_numbers"
     */
    public function testPropertyGlobalTradeItemNumbers()
    {
    }

    /**
     * Test attribute "rating_systems"
     */
    public function testPropertyRatingSystems()
    {
    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }

    /**
     * Test attribute "localisation_set"
     */
    public function testPropertyLocalisationSet()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "graphics"
     */
    public function testPropertyGraphics()
    {
    }

    /**
     * Test attribute "video_ur_ls"
     */
    public function testPropertyVideoUrLs()
    {
    }

    /**
     * Test attribute "restrictions"
     */
    public function testPropertyRestrictions()
    {
    }
}
